# Generated by Django 4.2.4 on 2023-09-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='ava',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ava',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='ava',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ava',
            new_name='img',
        ),
    ]
